/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { useState, useRef, type FormEvent, type ReactNode } from 'react';
import { motion, AnimatePresence } from 'motion/react';
import { 
  Sparkles, 
  Search, 
  Map, 
  Briefcase, 
  BookOpen, 
  FileText, 
  ChevronRight, 
  ChevronDown,
  Loader2, 
  GraduationCap,
  ArrowRight,
  BrainCircuit,
  Globe,
  CheckCircle2,
  Clock,
  Target,
  TrendingUp,
  Activity,
  Code,
  Cpu,
  Database,
  BarChart,
  Layout,
  Terminal,
  Shield,
  Layers,
  LineChart,
  Zap,
  Globe2,
  Share2,
  Copy,
  Mail,
  Twitter,
  Linkedin,
  FileDown
} from 'lucide-react';
import jsPDF from 'jspdf';
import html2canvas from 'html2canvas';
import { analyzeCareer, type CareerAnalysis } from './services/geminiService';

const ShareDialog = ({ roadmap, onClose }: { roadmap: CareerAnalysis, onClose: () => void }) => {
  const shareText = `Check out my personalized AI Career Roadmap for ${roadmap.recommendations[0].title}! Generated by Ascend.`;
  const shareUrl = window.location.href;

  const handleCopyLink = () => {
    navigator.clipboard.writeText(shareUrl);
    alert('Link copied to clipboard!');
  };

  const handleShare = async () => {
    if (navigator.share) {
      try {
        await navigator.share({
          title: 'My AI Career Roadmap',
          text: shareText,
          url: shareUrl,
        });
      } catch (err) {
        console.log('Error sharing:', err);
      }
    } else {
      handleCopyLink();
    }
  };

  return (
    <motion.div 
      initial={{ opacity: 0 }}
      animate={{ opacity: 1 }}
      exit={{ opacity: 0 }}
      className="fixed inset-0 z-[100] flex items-center justify-center p-6 bg-[rgba(15,23,42,0.6)] backdrop-blur-sm"
      onClick={onClose}
    >
      <motion.div 
        initial={{ scale: 0.9, y: 20 }}
        animate={{ scale: 1, y: 0 }}
        className="bg-white rounded-[32px] p-8 max-w-sm w-full shadow-2xl border border-slate-100"
        onClick={e => e.stopPropagation()}
      >
        <h3 className="text-xl font-bold mb-2">Share Roadmap</h3>
        <p className="text-sm text-app-text-secondary mb-8">Share your professional trajectory with your network.</p>
        
        <div className="grid grid-cols-2 gap-4 mb-8">
          <button 
            onClick={() => window.open(`https://twitter.com/intent/tweet?text=${encodeURIComponent(shareText)}&url=${encodeURIComponent(shareUrl)}`)}
            className="flex flex-col items-center gap-3 p-4 bg-slate-50 rounded-2xl hover:bg-app-accent-light hover:text-app-accent transition-all group"
          >
            <Twitter className="w-5 h-5" />
            <span className="text-[10px] font-bold uppercase tracking-widest">Twitter</span>
          </button>
          <button 
            onClick={() => window.open(`https://www.linkedin.com/sharing/share-offsite/?url=${encodeURIComponent(shareUrl)}`)}
            className="flex flex-col items-center gap-3 p-4 bg-slate-50 rounded-2xl hover:bg-app-accent-light hover:text-app-accent transition-all group"
          >
            <Linkedin className="w-5 h-5" />
            <span className="text-[10px] font-bold uppercase tracking-widest">LinkedIn</span>
          </button>
          <button 
            onClick={() => window.open(`mailto:?subject=My Career Roadmap&body=${encodeURIComponent(shareText + "\n\n" + shareUrl)}`)}
            className="flex flex-col items-center gap-3 p-4 bg-slate-50 rounded-2xl hover:bg-app-accent-light hover:text-app-accent transition-all group"
          >
            <Mail className="w-5 h-5" />
            <span className="text-[10px] font-bold uppercase tracking-widest">Email</span>
          </button>
          <button 
            onClick={handleShare}
            className="flex flex-col items-center gap-3 p-4 bg-slate-50 rounded-2xl hover:bg-app-accent-light hover:text-app-accent transition-all group"
          >
            <Share2 className="w-5 h-5" />
            <span className="text-[10px] font-bold uppercase tracking-widest">System</span>
          </button>
        </div>

        <button 
          onClick={handleCopyLink}
          className="w-full flex items-center justify-center gap-2 py-4 bg-slate-100 rounded-xl text-sm font-semibold hover:bg-slate-200 transition-colors"
        >
          <Copy className="w-4 h-4" />
          Copy Direct Link
        </button>
      </motion.div>
    </motion.div>
  );
};

const IconRenderer = ({ name, className }: { name: string, className?: string }) => {
  const icons: Record<string, ReactNode> = {
    Code: <Code className={className} />,
    Cpu: <Cpu className={className} />,
    Database: <Database className={className} />,
    BarChart: <BarChart className={className} />,
    Layout: <Layout className={className} />,
    Terminal: <Terminal className={className} />,
    Shield: <Shield className={className} />,
    Layers: <Layers className={className} />,
    LineChart: <LineChart className={className} />,
    Zap: <Zap className={className} />,
    Globe: <Globe2 className={className} />,
    TrendingUp: <TrendingUp className={className} />,
    Activity: <Activity className={className} />,
    Briefcase: <Briefcase className={className} />,
  };
  return icons[name] || <Briefcase className={className} />;
};

interface TimelineItemProps {
  key?: string | number;
  step: { action: string; detail: string };
  index: number;
  totalIndex: number;
  type: 'short' | 'long';
  isLast?: boolean;
}

const TimelineItem = ({ step, index, totalIndex, type, isLast }: TimelineItemProps) => {
  const [isExpanded, setIsExpanded] = useState(false);

  return (
    <motion.div 
      initial={{ opacity: 0, x: -10 }}
      animate={{ opacity: 1, x: 0 }}
      transition={{ delay: totalIndex * 0.1 }}
      className="relative flex gap-6 group"
    >
      <button 
        onClick={() => setIsExpanded(!isExpanded)}
        className={`z-10 shrink-0 w-8 h-8 rounded-full flex items-center justify-center font-bold text-[10px] shadow-sm transition-all duration-300 ring-4 ring-white ${
          type === 'short' 
            ? 'bg-white border-2 border-app-accent text-app-accent hover:bg-app-accent hover:text-white' 
            : 'bg-indigo-900 border-2 border-indigo-700 text-white hover:bg-indigo-800'
        }`}
      >
        {totalIndex + 1}
      </button>
      
      <div 
        className={`flex-1 p-4 rounded-xl border transition-all cursor-pointer ${
          isExpanded 
            ? (type === 'short' ? 'bg-white border-[rgba(79,70,229,0.3)] shadow-md' : 'bg-indigo-50 border-indigo-200 shadow-md')
            : (type === 'short' ? 'bg-app-slate-subtle border-slate-100 hover:border-[rgba(79,70,229,0.2)]' : 'bg-[rgba(238,242,255,0.2)] border-[rgba(238,242,255,0.5)] hover:border-indigo-100')
        }`}
        onClick={() => setIsExpanded(!isExpanded)}
      >
        <div className="flex justify-between items-start gap-4">
          <p className={`text-xs leading-relaxed ${type === 'long' ? 'font-medium' : ''}`}>
            {step.action}
          </p>
          <motion.div
            animate={{ rotate: isExpanded ? 180 : 0 }}
            className="shrink-0 pt-0.5"
          >
            <ChevronDown className={`w-3.5 h-3.5 ${type === 'short' ? 'text-app-accent' : 'text-indigo-600'}`} />
          </motion.div>
        </div>

        <AnimatePresence>
          {isExpanded && (
            <motion.div
              initial={{ height: 0, opacity: 0 }}
              animate={{ height: 'auto', opacity: 1 }}
              exit={{ height: 0, opacity: 0 }}
              className="overflow-hidden"
            >
              <div className="pt-3 mt-3 border-t border-slate-100">
                <p className="text-[11px] text-app-text-secondary leading-relaxed italic">
                  {step.detail}
                </p>
              </div>
            </motion.div>
          )}
        </AnimatePresence>
      </div>
    </motion.div>
  );
};

const RoadmapTimeline = ({ roadmap }: { roadmap: CareerAnalysis['roadmap'] }) => {
  return (
    <div className="relative py-4 pl-4">
      {/* Vertical Line */}
      <motion.div 
        initial={{ height: 0 }}
        animate={{ height: '100%' }}
        transition={{ duration: 1.5, ease: "easeInOut" }}
        className="absolute left-[31px] top-0 w-[2px] bg-slate-100 hidden sm:block"
      />
      
      <div className="space-y-12">
        <div className="space-y-8">
          <div className="flex items-center gap-3 mb-6">
            <div className="w-8 h-8 rounded-full bg-app-accent-light flex items-center justify-center text-app-accent">
              <Clock className="w-4 h-4" />
            </div>
            <h4 className="text-xs font-bold text-app-accent uppercase tracking-widest">{roadmap.shortTerm.title}</h4>
          </div>
          
          {roadmap.shortTerm.steps.map((step, i) => (
            <TimelineItem key={`short-${i}`} step={step} index={i} totalIndex={i} type="short" />
          ))}
        </div>

        <div className="space-y-8 relative">
          <div className="flex items-center gap-3 mb-6">
            <div className="w-8 h-8 rounded-full bg-indigo-900 flex items-center justify-center text-white">
              <Target className="w-4 h-4" />
            </div>
            <h4 className="text-xs font-bold text-app-text-muted uppercase tracking-widest">{roadmap.longTerm.title}</h4>
          </div>

          {roadmap.longTerm.steps.map((step, i) => (
            <TimelineItem 
              key={`long-${i}`} 
              step={step} 
              index={i} 
              totalIndex={roadmap.shortTerm.steps.length + i} 
              type="long" 
            />
          ))}
        </div>
      </div>
    </div>
  );
};

export default function App() {
  const [skills, setSkills] = useState('');
  const [interests, setInterests] = useState('');
  const [marks, setMarks] = useState('');
  const [isLoading, setIsLoading] = useState(false);
  const [results, setResults] = useState<CareerAnalysis | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [showShare, setShowShare] = useState(false);
  const [isGeneratingPDF, setIsGeneratingPDF] = useState(false);
  const reportRef = useRef<HTMLDivElement>(null);

  const handleDownloadPDF = async () => {
    if (!reportRef.current) return;
    setIsGeneratingPDF(true);
    
    try {
      const element = reportRef.current;
      
      // Capture with optimized settings
      const canvas = await html2canvas(element, {
        scale: 2,
        useCORS: true,
        logging: false,
        backgroundColor: '#ffffff',
        onclone: (clonedDoc) => {
          // Remove elements that shouldn't be in PDF
          const el = clonedDoc.getElementById('career-report-content');
          if (el) {
            el.style.height = 'auto';
            el.style.overflow = 'visible';
            el.style.padding = '20px';
          }
          // Disable animations globally in clone
          const style = clonedDoc.createElement('style');
          style.innerHTML = `
            * {
              animation: none !important;
              transition: none !important;
            }
          `;
          clonedDoc.head.appendChild(style);
        }
      });

      const imgData = canvas.toDataURL('image/jpeg', 1.0);
      const pdf = new jsPDF('p', 'mm', 'a4');
      
      const pageWidth = pdf.internal.pageSize.getWidth();
      const pageHeight = pdf.internal.pageSize.getHeight();
      const imgWidth = pageWidth;
      const imgHeight = (canvas.height * imgWidth) / canvas.width;
      
      let heightLeft = imgHeight;
      let position = 0;

      // First Page
      pdf.addImage(imgData, 'JPEG', 0, position, imgWidth, imgHeight);
      heightLeft -= pageHeight;

      // Extra Pages
      while (heightLeft >= 0) {
        position = heightLeft - imgHeight;
        pdf.addPage();
        pdf.addImage(imgData, 'JPEG', 0, position, imgWidth, imgHeight);
        heightLeft -= pageHeight;
      }

      // Filename construction
      const safeTitle = results?.recommendations[0].title.replace(/[^a-z0-9]/gi, '-').toLowerCase() || 'career-roadmap';
      
      // Direct Download Trigger
      pdf.save(`${safeTitle}-report.pdf`);
      
    } catch (err) {
      console.error('PDF Generation Error:', err);
      // Fallback to Window Print if programmatic PDF fails
      if (confirm('Direct PDF download encountered an issue. Would you like to use the system print dialog to "Save as PDF" instead?')) {
        window.print();
      }
    } finally {
      setIsGeneratingPDF(false);
    }
  };

  const handleSubmit = async (e: FormEvent) => {
    e.preventDefault();
    setIsLoading(true);
    setError(null);
    try {
      const data = await analyzeCareer(skills, interests, marks);
      setResults(data);
    } catch (err) {
      console.error(err);
      setError('Something went wrong while generating your roadmap. Please try again.');
    } finally {
      setIsLoading(false);
    }
  };

  const handleReset = () => {
    setResults(null);
    setSkills('');
    setInterests('');
    setMarks('');
    setShowShare(false);
  };

  return (
    <div className="flex flex-col h-screen bg-app-bg text-app-text-primary selection:bg-[rgba(79,70,229,0.1)]">
      <AnimatePresence>
        {showShare && results && (
          <ShareDialog roadmap={results} onClose={() => setShowShare(false)} />
        )}
      </AnimatePresence>

      {/* App Header */}
      <header className="bg-white border-b border-app-border px-8 py-5 flex justify-between items-center shrink-0 z-20">
        <div className="flex items-center gap-3">
          <div className="w-10 h-10 bg-app-accent rounded-lg flex items-center justify-center shadow-lg shadow-[rgba(79,70,229,0.2)]">
            <Sparkles className="w-6 h-6 text-white" />
          </div>
          <div>
            <h1 className="text-xl font-bold tracking-tight text-app-text-primary">Pathfinder AI</h1>
            <p className="text-[10px] text-app-text-muted font-bold uppercase tracking-widest">Advanced Career Guidance Engine</p>
          </div>
        </div>
        <div className="flex items-center gap-4 sm:gap-6">
          {results && (
            <>
              <div className="text-right hidden md:block">
                <p className="text-xs text-app-text-muted">Analysis Status</p>
                <p className="text-sm font-semibold flex items-center gap-1.5 justify-end">
                  <span className="w-2 h-2 rounded-full bg-emerald-500 animate-pulse" />
                  Completed
                </p>
              </div>
              <button 
                onClick={() => setShowShare(true)}
                className="p-2.5 bg-slate-50 text-app-text-primary hover:bg-slate-100 border border-slate-200 rounded-lg transition-colors flex items-center gap-2 group"
              >
                <Share2 className="w-4 h-4 text-app-accent group-hover:scale-110 transition-transform" />
                <span className="text-xs font-semibold hidden sm:inline">Share</span>
              </button>
              <button 
                onClick={handleDownloadPDF}
                disabled={isGeneratingPDF}
                className="p-2.5 bg-slate-800 text-white hover:bg-slate-900 rounded-lg transition-colors flex items-center gap-2 group disabled:opacity-50"
              >
                {isGeneratingPDF ? (
                  <Loader2 className="w-4 h-4 animate-spin" />
                ) : (
                  <FileDown className="w-4 h-4 text-emerald-400 group-hover:scale-110 transition-transform" />
                )}
                <span className="text-xs font-semibold hidden sm:inline">{isGeneratingPDF ? "Generating..." : "Save PDF"}</span>
              </button>
            </>
          )}
          <button 
            onClick={results ? handleReset : () => {}}
            className={`px-4 py-2.5 text-sm font-medium rounded-lg shadow-sm transition-all ${
              results 
                ? "bg-white border border-app-border text-app-text-primary hover:bg-slate-50" 
                : "bg-app-accent hover:bg-app-accent-hover text-white flex items-center gap-2"
            }`}
          >
            {results ? 'New Search' : (
              <>
                <Search className="w-4 h-4" />
                Insight Engine
              </>
            )}
          </button>
        </div>
      </header>

      {/* Main Layout */}
      <main className="flex-1 flex overflow-hidden">
        {/* Student Input Panel */}
        <aside className="w-80 bg-white border-r border-app-border p-6 flex flex-col gap-8 shrink-0 shadow-[4px_0_12px_rgba(0,0,0,0.02)] z-10 overflow-y-auto">
          <div>
            <h2 className="text-[11px] font-bold text-app-accent uppercase tracking-wider mb-4 border-b border-[rgba(79,70,229,0.1)] pb-2 flex items-center gap-2">
              <GraduationCap className="w-3 h-3" />
              Student Profile
            </h2>
            <div className="p-4 bg-slate-50 rounded-xl border border-slate-100 flex flex-col gap-4">
              <div className="flex items-center gap-3">
                <div className="w-10 h-10 rounded-full bg-app-accent-light flex items-center justify-center text-app-accent font-bold text-sm">
                  {results ? "JS" : "?"}
                </div>
                <div>
                  <div className="font-bold text-sm">{results ? "Student Profile" : "Awaiting Input"}</div>
                  <div className="text-[10px] text-app-text-secondary uppercase font-semibold">Verification level: AI-High</div>
                </div>
              </div>
            </div>
          </div>

          <form onSubmit={handleSubmit} className="space-y-6">
            <div className="space-y-2">
              <label className="text-[10px] font-bold text-app-text-muted uppercase tracking-widest flex items-center gap-2">
                <BrainCircuit className="w-3 h-3" />
                Current Skillset
              </label>
              <textarea 
                required
                value={skills}
                onChange={(e) => setSkills(e.target.value)}
                placeholder="Python, Public Speaking..."
                className="w-full bg-slate-50 border border-slate-200 rounded-lg p-3 text-sm focus:ring-2 ring-[rgba(79,70,229,0.2)] outline-none transition-all resize-none h-24"
              />
            </div>

            <div className="space-y-2">
              <label className="text-[10px] font-bold text-app-text-muted uppercase tracking-widest flex items-center gap-2">
                <Search className="w-3 h-3" />
                Primary Interests
              </label>
              <textarea 
                required
                value={interests}
                onChange={(e) => setInterests(e.target.value)}
                placeholder="Machine Learning, Ethics..."
                className="w-full bg-slate-50 border border-slate-200 rounded-lg p-3 text-sm focus:ring-2 ring-[rgba(79,70,229,0.2)] outline-none transition-all resize-none h-24"
              />
            </div>

            <div className="space-y-2">
              <label className="text-[10px] font-bold text-app-text-muted uppercase tracking-widest flex items-center gap-2">
                <GraduationCap className="w-3 h-3" />
                Academic Marks
              </label>
              <input 
                required
                type="text"
                value={marks}
                onChange={(e) => setMarks(e.target.value)}
                placeholder="GPA 3.9, A in CS..."
                className="w-full bg-slate-50 border border-slate-200 rounded-lg p-3 text-sm focus:ring-2 ring-[rgba(79,70,229,0.2)] outline-none transition-all"
              />
            </div>

            <button 
              disabled={isLoading}
              className="w-full py-3 bg-app-accent hover:bg-app-accent-hover text-white rounded-lg text-sm font-semibold shadow-md transition-all flex items-center justify-center gap-2 disabled:opacity-50"
            >
              {isLoading ? (
                <Loader2 className="w-4 h-4 animate-spin" />
              ) : (
                <>
                  Generate Roadmap
                  <ChevronRight className="w-4 h-4" />
                </>
              )}
            </button>
            {error && <p className="text-[10px] text-red-500 font-bold uppercase text-center">{error}</p>}
          </form>
        </aside>

        {/* Content Panel */}
        <section className="flex-1 p-8 overflow-y-auto">
          <AnimatePresence mode="wait">
            {!results ? (
              <motion.div 
                key="empty"
                initial={{ opacity: 0 }}
                animate={{ opacity: 1 }}
                className="h-full flex flex-col items-center justify-center text-center max-w-md mx-auto"
              >
                <div className="w-16 h-16 bg-white rounded-2xl flex items-center justify-center shadow-sm border border-app-border mb-6">
                  <BrainCircuit className="w-8 h-8 text-app-accent opacity-20" />
                </div>
                <h2 className="text-2xl font-bold mb-3">Ready for Intelligence</h2>
                <p className="text-sm text-app-text-secondary leading-relaxed">
                  Enter your academic credentials and professional aspirations in the sidebar to generate a complete career roadmap powered by Gemini 3.1 Pro.
                </p>
              </motion.div>
            ) : (
              <div ref={reportRef} id="career-report-content" className="bg-slate-50 p-4 rounded-3xl">
                <motion.div 
                  key="results"
                  initial={{ opacity: 0, y: 10 }}
                  animate={{ opacity: 1, y: 0 }}
                  className="max-w-5xl mx-auto space-y-6"
                >
                {/* Prime Recommendation */}
                <div className="bg-white rounded-2xl border border-app-border p-8 shadow-sm relative overflow-hidden flex flex-col md:flex-row gap-8 items-center">
                  <div className="absolute top-0 right-0 h-full w-1.5 bg-app-accent" />
                  <div className="flex-1">
                    <div className="flex items-center gap-2 mb-3">
                      <span className="px-2 py-0.5 bg-app-accent-light text-app-accent text-[10px] font-bold uppercase rounded tracking-wider">Prime Recommendation</span>
                      <span className="text-[10px] text-app-text-muted italic flex items-center gap-1">
                        <Globe className="w-3 h-3" />
                        Market Grounded
                      </span>
                    </div>
                    <h2 className="text-3xl font-bold text-app-text-primary">{results.recommendations[0].title}</h2>
                    <p className="text-sm text-app-text-secondary mt-3 leading-relaxed max-w-2xl">
                      {results.recommendations[0].description}
                    </p>
                    <div className="mt-4 p-3 bg-slate-50 rounded-lg border border-slate-100 text-[11px] italic text-app-text-secondary">
                      <span className="font-bold text-app-accent not-italic mr-2">Alignment:</span>
                      {results.recommendations[0].relevance}
                    </div>
                  </div>
                  <div className="w-32 h-32 rounded-full border-4 border-slate-50 flex items-center justify-center bg-white shrink-0">
                    <div className="text-center">
                      <Briefcase className="w-6 h-6 text-app-accent mx-auto mb-1" />
                      <div className="text-[10px] text-app-text-muted font-bold uppercase">Opportunity</div>
                    </div>
                  </div>
                </div>

                <div className="grid lg:grid-cols-2 gap-6">
                  {/* Development Roadmap */}
                  <div className="bg-white rounded-2xl border border-app-border flex flex-col overflow-hidden">
                    <div className="px-5 py-4 border-b border-app-border flex justify-between items-center bg-app-slate-subtle">
                      <h3 className="font-bold text-sm text-app-text-primary flex items-center gap-2">
                        <Map className="w-4 h-4 text-app-accent" />
                        Visual Roadmap
                      </h3>
                    </div>
                    <div className="p-6 flex-1">
                      <RoadmapTimeline roadmap={results.roadmap} />
                    </div>
                  </div>

                  {/* Opportunities & Courses */}
                  <div className="flex flex-col gap-6">
                    <div className="bg-white rounded-2xl border border-app-border p-6 shadow-sm">
                      <h3 className="font-bold text-sm text-app-text-primary mb-5 flex items-center gap-2">
                        <BookOpen className="w-4 h-4 text-app-accent" />
                        Learning Pipeline
                      </h3>
                      <div className="space-y-3">
                        {results.courses.map((course, i) => (
                          <div key={i} className="p-3 bg-slate-50 border border-slate-100 rounded-xl flex justify-between items-center group cursor-pointer hover:border-[rgba(79,70,229,0.3)] transition-all">
                            <div>
                              <p className="text-xs font-bold text-app-text-primary">{course.name}</p>
                              <p className="text-[10px] text-app-text-muted uppercase font-semibold">{course.platform}</p>
                            </div>
                            <ChevronRight className="w-4 h-4 text-app-accent opacity-0 group-hover:opacity-100 transition-all" />
                          </div>
                        ))}
                      </div>
                    </div>

                    <div className="bg-white rounded-2xl border border-app-border p-6 shadow-sm">
                      <h3 className="font-bold text-sm text-app-text-primary mb-5 flex items-center gap-2">
                        <Search className="w-4 h-4 text-app-accent" />
                        Market Entry
                      </h3>
                      <div className="space-y-6">
                        {results.jobs.map((job, i) => (
                          <div key={i} className="p-4 bg-slate-50 border border-slate-100 rounded-xl space-y-4 group">
                            <div className="flex items-start justify-between">
                              <div className="flex items-center gap-3">
                                <div className="p-2 bg-white rounded-lg border border-slate-200 text-app-accent shadow-sm group-hover:scale-110 transition-transform">
                                  <IconRenderer name={job.icon} className="w-4 h-4" />
                                </div>
                                <div>
                                  <p className="text-xs font-bold text-app-text-primary">{job.title}</p>
                                  <div className="flex flex-wrap gap-1 mt-1">
                                    {job.employers.slice(0, 2).map((emp, j) => (
                                      <span key={j} className="text-[8px] font-bold text-app-text-muted uppercase">
                                        {emp}{j < job.employers.slice(0, 2).length - 1 ? " • " : ""}
                                      </span>
                                    ))}
                                  </div>
                                </div>
                              </div>
                              <div className="text-right">
                                <div className="text-[9px] font-bold text-emerald-600 uppercase tracking-tight flex items-center gap-1">
                                  <TrendingUp className="w-3 h-3" />
                                  {job.growth}% Growth
                                </div>
                              </div>
                            </div>

                            {/* Growth Bar */}
                            <div className="space-y-1.5">
                              <div className="flex justify-between items-center text-[8px] uppercase tracking-widest font-bold text-app-text-muted">
                                <span>Market Demand</span>
                                <span>Visual Projection</span>
                              </div>
                              <div className="h-1.5 w-full bg-slate-200 rounded-full overflow-hidden">
                                <motion.div 
                                  initial={{ width: 0 }}
                                  animate={{ width: `${job.growth}%` }}
                                  transition={{ duration: 1, delay: 0.5 + i * 0.1 }}
                                  className="h-full bg-app-accent rounded-full shadow-[0_0_8px_rgba(79,70,229,0.3)]"
                                />
                              </div>
                            </div>
                          </div>
                        ))}
                      </div>
                    </div>

                    <div className="bg-indigo-900 text-white p-6 rounded-2xl relative overflow-hidden shadow-lg shadow-[rgba(30,27,75,0.2)]">
                      <div className="relative z-10">
                        <h3 className="text-[10px] font-bold text-indigo-300 uppercase tracking-widest mb-4 flex items-center gap-2">
                          <FileText className="w-3 h-3 text-indigo-400" />
                          Advisor's Strategic Tip
                        </h3>
                        <p className="text-sm leading-relaxed font-medium italic">
                          "{results.resumeTips[0]}"
                        </p>
                      </div>
                      <Sparkles className="absolute -right-4 -bottom-4 w-24 h-24 text-white opacity-[0.05]" />
                    </div>
                  </div>
                </div>

                {/* Additional Recommendations */}
                <div className="grid md:grid-cols-2 gap-6 pb-12">
                  {results.recommendations.slice(1).map((rec, i) => (
                    <div key={i} className="bg-white rounded-2xl border border-app-border p-6 shadow-sm">
                      <h4 className="font-bold text-sm text-app-text-primary mb-2 italic">Alternative Path: {rec.title}</h4>
                      <p className="text-xs text-app-text-secondary leading-relaxed">{rec.description}</p>
                    </div>
                  ))}
                </div>
              </motion.div>
            </div>
          )}
        </AnimatePresence>
        </section>
      </main>
    </div>
  );
}
